- zathura/zathura.c
This warning in Zathura is a nuisance for a number of reasons:
* Warning appears under perfectly normal conditions as you may not have made any bookmarks or may not use them
* Using Zathura as a PDF viewer with vim-latex can cause text to be written over the terminal when it shows this unnecessary warning as it repeatedly appears whenever the PDF is recompiled
* There are other warning and error messages for when the bookmarks file really can't be read
* `Failed to loads bookmarks` has an annoying typo
> Removing "Failed to loads bookmarks"

- doc/man/zathurarc.5.rst
- zathura/config.c
- zathura/zathura.c
Some of my zathura sessions are pretty long-running, e.g. when I have a textbook open, often more likely to close because of something crashing or because I run out of battery than because I intentionally close them, which means I lose my page. This fixes that problem, and hopefully other people will find this option useful as well.
> add continuous history save

- zathura/shortcuts.c
- zathura/utils.c
- zathura/utils.h
First step at fixing #430 
When open the index, the cursor is now at the row where the current page is contained
> feat: Highlight the current index row when toggling the index

- zathura/utils.c
The out_num argument is a guint64, which isn't the same as unsigned long on some platforms (e.g. AArch32 Linux).
> Fix type mismatch with g_ascii_string_to_unsigned

- zathura/shortcuts.c
- after EXPAND_ALL the current row can be out of view, so scroll to it
- COLLAPSE_ALL previously always shifted selected row to the top, now it stays put similarly as for COLLAPSE
Fixes #567.
> Fix: index row position after EXPAND_ALL/COLLAPSE_ALL

- zathura/seccomp-filters.c
Running zathura with strict sandbox settings on ARM devices requires a few different syscalls
> Add sandbox support for AArch64

- doc/man/zathura.1.rst
- zathura/config.c
- add aliases/abbreviations
- give further information about parameters
Fixes #581.
> Add missing commands to documentation

- zathura/seccomp-filters.c
Allows mremap as a requirement for mupdf. Fixes #585 
Also adds sysinfo which seems to be sometimes used during first run of zathura
> Add syscalls for mupdf

- zathura/callbacks.c
This fixes zoom breaking when page adjustment is active.
Repro:
- open any PDF
- press A or S to enable page adjustment
- try zooming by pinching on the touchpad
This gets zoom stuck in a weird broken state which can only be cleared by resizing the window.
I just copied this line over from sc_zoom(), but I wonder if a better fix isn't to simply call that? It's what scroll zoom does (including touchpad smooth scroll), and there's less potential for bugs if every zoom input takes the same code path.
> Disable page adjustment on gesture zoom

- zathura/main-sandbox.c
Prevents gtk_init() from opening a dbus socket connection that could potentially be used for sandbox escape
> Disable default gtk dbus connection

- zathura/shortcuts.c
The previous commit introducing numbered index navigation failed to consider cases when repeated tree path traversal or selection of the last child was necessary. This commit addresses this issue.
> Fix bugs introduced by numbered index navigation

- zathura/utils.c
Try to descend to the last child of the last index entry with `page of index entry` <= `current page`.
Fixes #613.
I am not completely sure, but it seems to me that this properly implements #430.
> Fix current index row selection

- zathura/seccomp-filters.c
Added ERRNO_RULE for _map_shadow_stack_ and _mseal_ syscalls in preparation of potential use on Linux kernel 6.10
> catch new syscalls

- zathura/shortcuts.c
- zathura/zathura.c
- implement number prefixed jumping
- do not try to jump to the "current" entry before jumping to
next/previous entry (this sometimes made the jumplist stuck)
Fixes #618.
> Jumplist rework

- zathura/utils.c
If the first index entry points to a page with `page > current page`, the `current_iter` would stay uninitialized, thus scrolling to current index row would throw errors.
Fixes #660.
> Fix current index row: always initialize

- zathura/page-widget.c
- zathura/page-widget.h
- zathura/shortcuts.c
- clear selected/highlighted region on abort
- proper clearing when transitioning between selection/highlighter
Fixes #599
Fixes #611
Fixes https://github.com/pwmt/zathura-djvu/issues/6
> Fix selection/highlighter behavior

- zathura/landlock.c
When zathura-sandbox is build with landlock support but the kernel does not include the landlock lsm, show an error to inform the user about the missing protection.
Partly fixes #654
> Add warning when landlock lsm is not available

- zathura/shortcuts.c
- zathura/utils.c
- zathura/zathura.c
- zathura/zathura.h
Fixes: #615 by making the scrolling to be execute after everything else
> Fix centering current index

- zathura/shortcuts.c
Previously, when scrolling with dual-page layout positioned in the exact center (for example obtained by best-fit adjustment), the boundary handling could change horizontal alignment in such a way that resulted in flickering of the page number between two visible pages.
This simple fix seems to work, however, I am not sure whether this is the best way. Other suggestions are welcome.
Fixes #646.
> Fix flickering page number

- zathura/page.c
Check if `page_label` is NULL before `strcmp`, as some page can have no label return by the plugin (the cover page for example)
> Check if page_label is NULL before strcmp

- zathura/utils.c
- zathura/zathura.c
- zathura/zathura.h
Also refactor `global.current_index_path` to be `GtkTreePath*`.
Fixes #675.
> Fix crash on simultaneous reload and index toggle

- zathura/config.c
Allows the browser keys on several older Thinkpads to be used as Page Up and Page Down.
> Added Browser keys

- zathura/shortcuts.c
- zathura/utils.c
- zathura/utils.h
This PR is a proof of concept for enabling search in index page. It only use the native functionality of `GTK`.
The behavior:
- Open the index page, press `C-f` (the default shortcut of `GTK`) to have the interactive search window appear
- Start typing the keyword, the index's cursor will jump to the first occurence,
- Disable interactive search by default so that when the search window is not present, all the keywords works normally (As opposed to before)
Partly fixes #565
> First step at enabling searching in index page

- zathura/callbacks.c
- zathura/dbus-interface.c
- zathura/dbus-interface.h
- zathura/synctex.c
- zathura/synctex.h
- zathura/zathura.c
- zathura/zathura.h
Fixes #685 .
The code is mostly copied from synctex's own code for new interactive feature.
A disadvantage I can think of is the scanner object consumes memory even when user is not looking up anything, but I think this is inevitable.
> Faster SyncTeX by reusing scanner object

- doc/man/zathurarc.5.rst
- zathura/config.c
- zathura/shortcuts.c
- zathura/shortcuts.h
Closes #707 
Adds a file chooser function which can be mapped in zathurarc.
Tested on arch linux.
> File Chooser Dialog

- meson.build
- zathura/main-sandbox.c
The zathura-sandbox now builds on OpenBSD and has essential pledge(2) support, effectively restricting system calls to the bare minimum.
In its prior state, the zathura-sandbox only supported Linux. This made a change of build requirements necessary, which now also checks if the target machine is OpenBSD.
Within the init_zathura function of the sandbox, a new ifdef for OpenBSD has been introduced, reducing the available system calls to a bare minimum using pledge(2). After that, files can still be opened, but nothing more.
Fortunately, due to the architecture of the sandbox, this is sufficient, as the PDF libraries and UI were already rendered. Suspicious PDF files loaded afterwards should do no harm.
The patched zathura-sandbox version was tested against multiple PDF files using the …
> zathura-sandbox: Initial OpenBSD Support

- zathura/shortcuts.c
Fix #731 .
When the current path iter does not have a next iter (last item in the current level), move to the next iter of the first parent of the current iter which has a next iter if it exists, otherwise don't change the current path.
Side note: when looking into this I was confused why it was working for down arrow and not j, what I found is `GDK_KEY_Down` does not call `sc_navigate_index`, nor is it processed by `girara_callback_view_key_press_event`. I'm not sure how that is making changes to the index, using the gtk debugger the key press is counted by the main GtkWindow but nothing else (including the GtkScrolledWindow which is session.gtk->view).
> fix cycling through last sub-item on index

- zathura/callbacks.c
- zathura/document-widget.c
- zathura/zathura.c
Fixes #751 
Scroll bottom doesn't update the current page number before the document widget is rendered, so we use the document position to get the current page number instead.
Search position was more difficult. When searching, if the document grid changes, the vadjustment would not have updated to reflect the current size of the grid resulting in incorrect adjustments. It seems like changing the set adjustment to update on the mainloop using `g_idle_add_once` fixes this. I'm not sure if this is the right way to solve this, or if get adjustment should also be in the mainloop, open to feedback.
> Scroll search

- doc/man/zathurarc.5.rst
- zathura/config.c
- zathura/render.c
- zathura/render.h
- zathura/zathura.c
Some thinner fonts (e.g., Computer Modern Roman) can be harder to read when recoloring. This implements the option `recolor-adjust-lightness`, which adjusts the lightness before recoloring, improving readability.
The adjustment is implemented with a quartic curve. The adjusted lightness is then averaged against the original lightness, weighed by saturation, which makes colors less “washed out” (this was particularly annoying for graphics like TikZ). The weighing is not implemented when “recolor-keephue” is disabled for technical reasons, although it also improves the readability of darker colors.
Fixes #276
Note: rewritten June 6th, June 9th.
> feat(render): optional lightness adjustment when recoloring

- zathura/adjustment.c
- zathura/adjustment.h
- zathura/callbacks.c
- zathura/document-widget.c
- zathura/document-widget.h
- zathura/shortcuts.c
- zathura/zathura.c
Resolves #766 
Document widget previously didn't calculate the x and y position for the grid correctly.
Compute a set of rows to place in the grid, and fill each row with pages to avoid partially filled rows.
Smooth scrolling wouldn't trigger a document widget render causing scrolling to get stuck at the end of grid. 
Updated the render range calculation to be calculated directly from current document position rather than checking every page for visibility which may cause issues with large documents.
> document widget updates

- zathura/zathura.c
Resolves #785 
`cb_view_resized` is not called when a girara notification occurs, since the window size remains the same
> update view when session view size changes

- tests/meson.build
- zathura/seccomp-filters.c
The second xvfb test that runs sandboxed appears to ignore the runtime check https://github.com/pwmt/zathura/blob/0ff313ffdfee6eaa733ba7b9f911115c7f777c38/zathura/seccomp-filters.c#L156 when running under wayland
Without this check the test fails when running under wayland because xvfb wants the mprotect syscall with executable memory permissions
> Remove sandboxed xvfb test 
